### ISSUE TITLE
Floating GPIO Pins

### ISSUE THREAD

**Issue by rauhul** [acm-uiuc/SIGBot-2016-2017#16]
Currently after making a digital keypress the pi's gpio pins take on ~1.3v when they should be low (0v).

Not known if this is a manufacturing issue or a design bug.

**Comment by abrandemuehl** [comment]
Raspberry PI has internal pull resistors. We can use them by using a third argument in the pin setup function
Example: `GPIO.setup(17, GPIO.IN, pull_up_down=GPIO.PUD_UP)`

Reference: https://learn.sparkfun.com/tutorials/raspberry-gpio/python-rpigpio-api

Not sure if that will fix it

**Comment by abrandemuehl** [comment]
What ground is that 1.3v referenced to?

**Comment by rauhul** [comment]
The machine and the rpi share a ground

**Comment by rauhul** [comment]
This bug appeared due to incorrect testing methodology. Since the test vend script only assigns value to rPi's GPIO pins while its running (i.e. the take no value after the script has ended), we see floating values on these pins.

This appears to the root cause of the vend failures and various other bugs.

**Comment by narendasan** [comment]
But we tested in console without the script as well, didn't we detect the issue there (don't remember myself)? Have we tested with the server? Also shouldn't tear down of the gpio library address floating values on the gpio? It seems there is still inconsistent behavior (unless you have tested the boards more formally than running in console and with the sample script). We should also make sure the test script is modified to be more close to how the server will work.

**Comment by narendasan** [comment]
If it is indeed an issue with cleanup, then the bug is testing will appear in  app.py as well. Root cause is that the Python interpreter does not guarantee that destructors of global instances will be called when the app terminates. It is in the destructor of merch that we call GPIO.cleanup. Since both app.py and vend_merch use a global instance, floating GPIO should be expected with both. The solution is to initialize execution in a context (using with) and changing the __del__ method to __exit__. Source: https://stackoverflow.com/questions/3554952/del-at-program-end. I am still not convinced this address vend failures with the new board
